version: "3"
services:
  syncthing:
    image: syncthing/syncthing:1.30@sha256:74eeedb08d4912763055594f8bd98bfc039f3bc504b6cd2c2adc8294111c1251
    container_name: syncthing
    hostname: syncthing-vds
    environment:
      - PUID=1000 #I use docker remap. syncthing uid = 166536 = 1000 in docker container
      - PGID=1000 #Same for group here
      - TZ=Europe/Moscow
      - STGUIADDRESS=https://0.0.0.0:8384
    volumes:
        - /docker/syncthing/config/:/var/syncthing
        - /docker/syncthing/data/:/mnt
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
